version: '2'
services:
  openvpn_bridged:
    image: livemps/mps-openvpn
    container_name: openvpn_bridged
    restart: always
    hostname: 'openvpn_bridged'
    entrypoint: bash -c "cd /etc/openvpn/server/$OPENVPN_DOMAIN && openvpn --config ${OPENVPN_DOMAIN}_bridged.conf"
    volumes:
      - '$DATA_FOLDER/certs/$OPENVPN_DOMAIN/srv:/etc/openvpn/server/$OPENVPN_DOMAIN'
      - '$DATA_FOLDER/logs/:/var/log/openvpn/'
    network_mode: "host"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
  openvpn_ptp:
    image: livemps/mps-openvpn
    container_name: openvpn_ptp
    restart: always
    hostname: 'openvpn_ptp'
    entrypoint: bash -c "cd /etc/openvpn/server/$OPENVPN_DOMAIN && openvpn --config ${OPENVPN_DOMAIN}_ptp.conf"
    volumes:
      - '$DATA_FOLDER/certs/$OPENVPN_DOMAIN/srv:/etc/openvpn/server/$OPENVPN_DOMAIN'
      - '$DATA_FOLDER/logs/:/var/log/openvpn/'
    network_mode: "host"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
